// Module 4 — Postflop Decision Trainer (CLAUDE.md §4).
//
// Three selectable drills (C-bet Decision, Facing a Bet, Bet Sizing). Each spot is
// generated by ./drills.js, graded instantly against the documented HEURISTIC
// default lines (labelled as such — this is not a solver), and wired into the
// shared store for progress + leak tracking. Layout mirrors the other trainers'
// setup → playing → summary flow.

import { useState } from 'react'
import Card from '../../components/Card.jsx'
import { getProgress, recordAttempt, recordLeak, resetProgress, clearLeaks } from '../../store'
import {
  DRILL_TYPES,
  TYPE_LABEL,
  LEAK_PREFIX,
  ANSWERS,
  nextSpot,
  gradeSpot,
  leakEntriesForMiss,
} from './drills.js'

const MODULE_ID = 'postflop-trainer'
const SESSION_LENGTHS = [10, 25, 50, 100]

// The heuristic disclaimer, shown on setup + while playing (spec requirement).
const DISCLAIMER = 'Heuristic default lines, not GTO-perfect.'

// Drill options for the setup screen. `null` = All (mixed) — the default.
const DRILL_OPTIONS = [
  { label: 'All (mixed)', value: null },
  ...DRILL_TYPES.map((t) => ({ label: TYPE_LABEL[t], value: t })),
]

const emptyStats = () => ({ answered: 0, correct: 0 })

export default function PostflopTrainer() {
  const [phase, setPhase] = useState('setup') // 'setup' | 'playing' | 'summary'
  const [length, setLength] = useState(25)
  const [drill, setDrill] = useState(null) // null = All (mixed); else a DRILL_TYPES value
  const [spot, setSpot] = useState(null)
  const [generating, setGenerating] = useState(false)
  const [result, setResult] = useState(null) // { correct, correctText, explain }
  const [stats, setStats] = useState(emptyStats)
  const [sessionMisses, setSessionMisses] = useState({}) // drill type -> count
  const [lifetime, setLifetime] = useState(() => getProgress(MODULE_ID).accuracy)
  const [confirmingReset, setConfirmingReset] = useState(false)

  // Facing/sizing generation re-deals to hit clean spots; defer to a tick so the
  // "Dealing…" state can paint. Uniform path for every drill type.
  const loadNext = () => {
    setGenerating(true)
    setResult(null)
    setTimeout(() => {
      setSpot(nextSpot(drill))
      setGenerating(false)
    }, 0)
  }

  const start = (len) => {
    setLength(len)
    setStats(emptyStats())
    setSessionMisses({})
    setPhase('playing')
    loadNext()
  }

  const submit = (value) => {
    if (result || !spot) return // already graded, or nothing to grade
    const res = gradeSpot(spot, value)

    const progress = recordAttempt(MODULE_ID, { correct: res.correct })
    setLifetime(progress.accuracy)
    setStats((s) => ({ answered: s.answered + 1, correct: s.correct + (res.correct ? 1 : 0) }))

    if (!res.correct) {
      for (const { tag, meta } of leakEntriesForMiss(spot)) recordLeak(tag, meta)
      setSessionMisses((m) => ({ ...m, [spot.type]: (m[spot.type] ?? 0) + 1 }))
    }

    setResult(res)
  }

  const next = () => {
    if (stats.answered >= length) {
      setPhase('summary')
      return
    }
    loadNext()
  }

  // Clear only the postflop-trainer's stored progress and its own leaks (tags with
  // the postflop_ prefix); other modules' data is untouched.
  const confirmReset = () => {
    resetProgress(MODULE_ID)
    clearLeaks((leak) => leak.tag.startsWith(LEAK_PREFIX))
    setLifetime(getProgress(MODULE_ID).accuracy)
    setConfirmingReset(false)
  }

  const sessionAcc = stats.answered ? (100 * stats.correct) / stats.answered : 0
  const worstMisses = Object.entries(sessionMisses)
    .map(([type, count]) => ({ type, count }))
    .sort((a, b) => b.count - a.count)

  // ---------- setup ----------
  if (phase === 'setup') {
    return (
      <Shell>
        <h1 className="pt-title">Postflop Decision Trainer</h1>
        <p className="pt-subtitle">C-bets, facing bets & sizing — solid default lines</p>
        <p className="mt-1 text-xs uppercase tracking-wide text-amber-300">{DISCLAIMER}</p>

        <p className="mt-6 text-sm text-emerald-200">Choose a drill:</p>
        <div className="mt-2 flex flex-wrap justify-center gap-2">
          {DRILL_OPTIONS.map((opt) => {
            const active = drill === opt.value
            return (
              <button
                key={opt.label}
                onClick={() => setDrill(opt.value)}
                className={`pt-toggle ${active ? 'pt-toggle-on' : 'pt-toggle-off'}`}
              >
                {opt.label}
              </button>
            )
          })}
        </div>

        <p className="mt-6 text-sm text-emerald-200">Choose a session length:</p>
        <div className="mt-2 flex flex-wrap justify-center gap-3">
          {SESSION_LENGTHS.map((len) => (
            <button
              key={len}
              onClick={() => start(len)}
              className="pt-btn pt-btn-light"
            >
              {len} spots
            </button>
          ))}
        </div>

        <div className="mt-6 flex flex-col items-center gap-1">
          <p className="text-xs text-emerald-300">Lifetime accuracy: {lifetime.toFixed(1)}%</p>
          {!confirmingReset ? (
            <button
              onClick={() => setConfirmingReset(true)}
              className="text-xs text-emerald-400 underline underline-offset-2 hover:text-emerald-200"
            >
              Reset lifetime stats
            </button>
          ) : (
            <div className="mt-1 flex flex-col items-center gap-2 rounded-lg bg-emerald-950/40 px-4 py-3">
              <p className="max-w-xs text-center text-xs text-emerald-100">
                This clears all saved progress and leaks for the postflop trainer — are you sure?
              </p>
              <div className="flex gap-2">
                <button
                  onClick={confirmReset}
                  className="rounded-lg bg-rose-500 px-3 py-1.5 text-xs font-semibold text-white shadow hover:bg-rose-400"
                >
                  Yes, reset
                </button>
                <button
                  onClick={() => setConfirmingReset(false)}
                  className="rounded-lg bg-white px-3 py-1.5 text-xs font-semibold text-emerald-900 shadow hover:bg-emerald-50"
                >
                  Cancel
                </button>
              </div>
            </div>
          )}
        </div>
      </Shell>
    )
  }

  // ---------- summary ----------
  if (phase === 'summary') {
    return (
      <Shell>
        <h1 className="pt-title">Session complete</h1>
        <div className="mt-4 pt-card p-5 text-center">
          <div className="text-4xl font-bold text-emerald-700">{sessionAcc.toFixed(0)}%</div>
          <div className="text-sm text-gray-600">
            {stats.correct}/{stats.answered} correct · lifetime {lifetime.toFixed(1)}%
          </div>
        </div>

        <div className="mt-4 w-full max-w-sm pt-card p-4">
          <div className="text-sm font-semibold text-gray-800">Weakest drills this session</div>
          {worstMisses.length === 0 ? (
            <div className="mt-1 text-sm text-emerald-700">No misses — clean session! 🎉</div>
          ) : (
            <ul className="mt-2 space-y-1 text-sm text-gray-700">
              {worstMisses.map((m) => (
                <li key={m.type} className="flex justify-between">
                  <span>{TYPE_LABEL[m.type]}</span>
                  <span className="tabular-nums text-red-600">×{m.count}</span>
                </li>
              ))}
            </ul>
          )}
        </div>

        <button
          onClick={() => setPhase('setup')}
          className="mt-6 pt-btn pt-btn-light"
        >
          New session
        </button>
      </Shell>
    )
  }

  // ---------- playing ----------
  const spotNo = Math.min(stats.answered + (result ? 0 : 1), length)
  return (
    <Shell>
      <div className="flex w-full max-w-md items-center justify-between text-sm text-emerald-100">
        <span>
          Spot {spotNo} / {length}
        </span>
        <span>
          Session {sessionAcc.toFixed(0)}% · Lifetime {lifetime.toFixed(0)}%
        </span>
      </div>

      {generating || !spot ? (
        <div className="mt-16 text-emerald-100">Dealing…</div>
      ) : (
        <>
          <div className="mt-4 flex items-center gap-2 text-xs uppercase tracking-wide">
            <span className="text-emerald-300">{TYPE_LABEL[spot.type]}</span>
            <span className="text-amber-300/70">· {DISCLAIMER}</span>
          </div>

          <div className="mt-3 w-full max-w-md">{renderPrompt(spot)}</div>

          {!result ? (
            <div className="mt-6 w-full max-w-md">
              <AnswerButtons type={spot.type} onPick={submit} />
            </div>
          ) : (
            <div className="mt-6 flex w-full max-w-md flex-col items-center gap-3">
              <div
                className={`w-full rounded-xl p-4 text-center shadow-lg ${
                  result.correct ? 'bg-emerald-50' : 'bg-rose-50'
                }`}
              >
                <div
                  className={`text-lg font-bold ${
                    result.correct ? 'text-emerald-700' : 'text-rose-700'
                  }`}
                >
                  {result.correct ? 'Correct' : 'Incorrect'} — {result.correctText}
                </div>
                <div className="mt-1 text-sm text-gray-700">{result.explain}</div>
              </div>
              <button
                onClick={next}
                className="rounded-xl bg-white px-8 py-3 font-semibold text-emerald-900 shadow hover:bg-emerald-50"
              >
                {stats.answered >= length ? 'See summary' : 'Next spot'}
              </button>
            </div>
          )}
        </>
      )}
    </Shell>
  )
}

// ---------- per-drill prompt rendering ----------

function renderPrompt(spot) {
  switch (spot.type) {
    case 'cbet':
      return (
        <div className="flex flex-col items-center gap-4 rounded-xl bg-emerald-950/40 p-5">
          <div className="text-center text-sm text-emerald-100">
            {spot.scenario.text} You are the preflop raiser.
          </div>
          <HandAndBoard hole={spot.hole} board={spot.board} boardLabel="Flop" />
          <div className="text-center text-sm font-semibold text-emerald-50">
            Do you continuation-bet, or check?
          </div>
        </div>
      )
    case 'facing':
      return (
        <div className="flex flex-col items-center gap-4 rounded-xl bg-emerald-950/40 p-5">
          <div className="text-center text-sm text-emerald-100">
            You called a raise. On the {spot.street}, your opponent bets{' '}
            <span className="font-bold text-white">{spot.betLabel}</span>.
          </div>
          <HandAndBoard hole={spot.hole} board={spot.board} boardLabel={spot.street[0].toUpperCase() + spot.street.slice(1)} />
          <div className="text-center text-sm font-semibold text-emerald-50">Call, raise, or fold?</div>
        </div>
      )
    case 'sizing':
      return (
        <div className="flex flex-col items-center gap-4 rounded-xl bg-emerald-950/40 p-5">
          <div className="text-center text-sm text-emerald-100">
            Betting is correct here — you're{' '}
            <span className="font-bold text-white">
              {spot.role === 'value' ? 'value-betting' : 'semi-bluffing'}
            </span>
            . Which size?
          </div>
          <HandAndBoard hole={spot.hole} board={spot.board} boardLabel="Flop" />
          <div className="text-center text-sm font-semibold text-emerald-50">
            Pick a bet size (fraction of the pot).
          </div>
        </div>
      )
    default:
      return null
  }
}

// ---------- answer buttons per drill ----------

function AnswerButtons({ type, onPick }) {
  const options = ANSWERS[type]
  // Sizing has four compact options; cbet/facing use larger primary buttons.
  const compact = type === 'sizing'
  return (
    <div className="flex flex-wrap justify-center gap-3">
      {options.map((opt) => (
        <button
          key={opt.value}
          onClick={() => onPick(opt.value)}
          className={`rounded-xl font-bold text-white shadow transition ${
            compact ? 'px-6 py-3 text-xl' : 'px-8 py-3 text-lg'
          } ${buttonColor(opt.value)}`}
        >
          {opt.label}
        </button>
      ))}
    </div>
  )
}

// Colour by intent: aggressive greens, fold reds, neutral for sizes/check.
function buttonColor(value) {
  if (value === 'cbet' || value === 'call' || value === 'raise') return 'bg-emerald-500 hover:bg-emerald-400'
  if (value === 'fold') return 'bg-rose-500 hover:bg-rose-400'
  if (value === 'check') return 'bg-sky-500 hover:bg-sky-400'
  return 'bg-emerald-600 hover:bg-emerald-500' // sizing options
}

function HandAndBoard({ hole, board, boardLabel }) {
  return (
    <div className="flex flex-col items-center gap-3">
      <div className="flex flex-col items-center gap-1">
        <span className="text-xs uppercase tracking-wide text-emerald-300">Your hand</span>
        <div className="flex gap-2">
          {hole.map((c) => (
            <Card key={c} card={c} size="md" />
          ))}
        </div>
      </div>
      <div className="flex flex-col items-center gap-1">
        <span className="text-xs uppercase tracking-wide text-emerald-300">{boardLabel}</span>
        <div className="flex gap-2">
          {board.map((c) => (
            <Card key={c} card={c} size="sm" />
          ))}
        </div>
      </div>
    </div>
  )
}

// Shared page frame (matches the other trainers).
function Shell({ children }) {
  return <div className="pt-screen pt-screen-center">{children}</div>
}
