// Module 3 — Board Texture & Hand Reading Trainer (CLAUDE.md §4).
//
// Three drills (Texture ID, What Beats You, Range Interaction). Each spot is
// generated by ./drills.js, graded instantly, and wired into the shared store for
// progress + leak tracking. Layout mirrors the Range / Odds trainers'
// setup → playing → summary flow. Texture and Range grading are HEURISTIC (labelled
// as such in the UI); What Beats You is exact evaluator truth.

import { useState } from 'react'
import Card from '../../components/Card.jsx'
import Term from '../../components/Term.jsx'
import { getProgress, recordAttempt, recordLeak, resetProgress, clearLeaks } from '../../store'
import {
  DRILL_TYPES,
  TYPE_LABEL,
  LEAK_PREFIX,
  TEXTURE_TAGS,
  HAND_CLASSES,
  nextSpot,
  gradeSpot,
  leakEntriesForMiss,
} from './drills.js'

const MODULE_ID = 'board-reader'
const SESSION_LENGTHS = [10, 25, 50, 100]

// Which drills lean on a reviewable heuristic (vs. exact evaluator truth).
const HEURISTIC_TYPES = new Set(['texture', 'range'])

const DRILL_OPTIONS = [
  { label: 'All (mixed)', value: null },
  ...DRILL_TYPES.map((t) => ({ label: TYPE_LABEL[t], value: t })),
]

const emptyStats = () => ({ answered: 0, correct: 0 })

export default function BoardReader() {
  const [phase, setPhase] = useState('setup') // 'setup' | 'playing' | 'summary'
  const [length, setLength] = useState(25)
  const [drill, setDrill] = useState(null) // null = All (mixed); else a DRILL_TYPES value
  const [spot, setSpot] = useState(null)
  const [generating, setGenerating] = useState(false)
  const [selected, setSelected] = useState([]) // toggled tags/classes for multi-select drills
  const [result, setResult] = useState(null) // { correct, correctText, explain }
  const [stats, setStats] = useState(emptyStats)
  const [sessionMisses, setSessionMisses] = useState({}) // drill type -> count
  const [lifetime, setLifetime] = useState(() => getProgress(MODULE_ID).accuracy)
  const [confirmingReset, setConfirmingReset] = useState(false)

  // Generating the "what beats you" spot enumerates ~1000 holdings, so defer a tick
  // so the "Dealing…" state can paint first. Uniform path for every drill type.
  const loadNext = () => {
    setGenerating(true)
    setSelected([])
    setResult(null)
    setTimeout(() => {
      setSpot(nextSpot(drill))
      setGenerating(false)
    }, 0)
  }

  const start = (len) => {
    setLength(len)
    setStats(emptyStats())
    setSessionMisses({})
    setPhase('playing')
    loadNext()
  }

  const submit = (answer) => {
    if (result || !spot) return
    const res = gradeSpot(spot, answer)

    const progress = recordAttempt(MODULE_ID, { correct: res.correct })
    setLifetime(progress.accuracy)
    setStats((s) => ({ answered: s.answered + 1, correct: s.correct + (res.correct ? 1 : 0) }))

    if (!res.correct) {
      leakEntriesForMiss(spot).forEach((e) => recordLeak(e.tag, e.meta))
      setSessionMisses((m) => ({ ...m, [spot.type]: (m[spot.type] ?? 0) + 1 }))
    }

    setResult(res)
  }

  const next = () => {
    if (stats.answered >= length) {
      setPhase('summary')
      return
    }
    loadNext()
  }

  // Clear only this module's progress + its own leaks (the board_ prefix).
  const confirmReset = () => {
    resetProgress(MODULE_ID)
    clearLeaks((leak) => leak.tag.startsWith(LEAK_PREFIX))
    setLifetime(getProgress(MODULE_ID).accuracy)
    setConfirmingReset(false)
  }

  const toggle = (value) =>
    setSelected((sel) => (sel.includes(value) ? sel.filter((v) => v !== value) : [...sel, value]))

  const sessionAcc = stats.answered ? (100 * stats.correct) / stats.answered : 0
  const worstMisses = Object.entries(sessionMisses)
    .map(([type, count]) => ({ type, count }))
    .sort((a, b) => b.count - a.count)

  // ---------- setup ----------
  if (phase === 'setup') {
    return (
      <Shell>
        <h1 className="pt-title">Board Texture &amp; Hand Reading</h1>
        <p className="pt-subtitle">Read the board — texture, what beats you, and range advantage</p>
        <p className="mt-1 max-w-md text-center text-xs text-onfelt-3">
          Texture &amp; range reads are graded on documented heuristics (not a solver). “What beats
          you” is exact.
        </p>

        <p className="mt-6 text-sm text-onfelt-2">Choose a drill:</p>
        <div className="mt-2 flex flex-wrap justify-center gap-2">
          {DRILL_OPTIONS.map((opt) => {
            const active = drill === opt.value
            return (
              <button
                key={opt.label}
                onClick={() => setDrill(opt.value)}
                className={`pt-toggle ${active ? 'pt-toggle-on' : 'pt-toggle-off'}`}
              >
                {opt.label}
              </button>
            )
          })}
        </div>

        <p className="mt-6 text-sm text-onfelt-2">Choose a session length:</p>
        <div className="mt-2 flex flex-wrap justify-center gap-3">
          {SESSION_LENGTHS.map((len) => (
            <button
              key={len}
              onClick={() => start(len)}
              className="pt-btn pt-btn-light"
            >
              {len} spots
            </button>
          ))}
        </div>

        <div className="mt-6 flex flex-col items-center gap-1">
          <p className="text-xs text-onfelt-3">Lifetime accuracy: {lifetime.toFixed(1)}%</p>
          {!confirmingReset ? (
            <button
              onClick={() => setConfirmingReset(true)}
              className="text-xs text-onfelt-4 underline underline-offset-2 hover:text-onfelt-2"
            >
              Reset lifetime stats
            </button>
          ) : (
            <div className="mt-1 flex flex-col items-center gap-2 rounded-lg bg-panel/40 px-4 py-3">
              <p className="max-w-xs text-center text-xs text-onfelt-2">
                This clears all saved progress and leaks for the board reader — are you sure?
              </p>
              <div className="flex gap-2">
                <button
                  onClick={confirmReset}
                  className="rounded-lg bg-danger-solid px-3 py-1.5 text-xs font-semibold text-onfelt shadow hover:bg-danger-hover"
                >
                  Yes, reset
                </button>
                <button
                  onClick={() => setConfirmingReset(false)}
                  className="rounded-lg bg-surface px-3 py-1.5 text-xs font-semibold text-ink-heading shadow hover:bg-surface-inset"
                >
                  Cancel
                </button>
              </div>
            </div>
          )}
        </div>
      </Shell>
    )
  }

  // ---------- summary ----------
  if (phase === 'summary') {
    return (
      <Shell>
        <h1 className="pt-title">Session complete</h1>
        <div className="mt-4 pt-card p-5 text-center">
          <div className="text-4xl font-bold text-accent-text">{sessionAcc.toFixed(0)}%</div>
          <div className="text-sm text-ink-body">
            {stats.correct}/{stats.answered} correct · lifetime {lifetime.toFixed(1)}%
          </div>
        </div>

        <div className="mt-4 w-full max-w-sm pt-card p-4">
          <div className="text-sm font-semibold text-ink">Weakest drills this session</div>
          {worstMisses.length === 0 ? (
            <div className="mt-1 text-sm text-accent-text">No misses — clean session! 🎉</div>
          ) : (
            <ul className="mt-2 space-y-1 text-sm text-ink-body">
              {worstMisses.map((m) => (
                <li key={m.type} className="flex justify-between">
                  <span>{TYPE_LABEL[m.type]}</span>
                  <span className="tabular-nums text-danger">×{m.count}</span>
                </li>
              ))}
            </ul>
          )}
        </div>

        <button
          onClick={() => setPhase('setup')}
          className="mt-6 pt-btn pt-btn-light"
        >
          New session
        </button>
      </Shell>
    )
  }

  // ---------- playing ----------
  const spotNo = Math.min(stats.answered + (result ? 0 : 1), length)
  return (
    <Shell>
      <div className="flex w-full max-w-md items-center justify-between text-sm text-onfelt-2">
        <span>
          Spot {spotNo} / {length}
        </span>
        <span>
          Session {sessionAcc.toFixed(0)}% · Lifetime {lifetime.toFixed(0)}%
        </span>
      </div>

      {generating || !spot ? (
        <div className="mt-16 text-onfelt-2">Dealing…</div>
      ) : (
        <>
          <div className="mt-4 flex items-center gap-2 text-xs uppercase tracking-wide text-onfelt-3">
            {TYPE_LABEL[spot.type]}
            {HEURISTIC_TYPES.has(spot.type) && (
              <span className="rounded bg-panel/60 px-1.5 py-0.5 text-[10px] normal-case tracking-normal text-onfelt-3">
                heuristic
              </span>
            )}
          </div>

          <div className="mt-3 w-full max-w-md">{renderPrompt(spot)}</div>

          {!result ? (
            <div className="mt-6 w-full max-w-md">
              {renderInput(spot, { selected, toggle, submit })}
            </div>
          ) : (
            <div className="mt-6 flex w-full max-w-md flex-col items-center gap-3">
              <div
                className={`w-full rounded-xl p-4 text-center shadow-lg ${
                  result.correct ? 'bg-surface-inset' : 'bg-danger-soft'
                }`}
              >
                <div className={`text-lg font-bold ${result.correct ? 'text-accent-text' : 'text-danger-text'}`}>
                  {result.correct ? 'Correct' : 'Incorrect'} — {result.correctText}
                </div>
                <div className="mt-1 text-sm text-ink-body">{result.explain}</div>
              </div>
              <button
                onClick={next}
                className="rounded-xl bg-surface px-8 py-3 font-semibold text-ink-heading shadow hover:bg-surface-inset"
              >
                {stats.answered >= length ? 'See summary' : 'Next spot'}
              </button>
            </div>
          )}
        </>
      )}
    </Shell>
  )
}

// ---------- per-drill prompt rendering ----------

function renderPrompt(spot) {
  switch (spot.type) {
    case 'texture':
      return (
        <div className="flex flex-col items-center gap-4 rounded-xl bg-panel/40 p-5">
          <BoardRow cards={spot.board} />
          <div className="text-center text-sm text-onfelt-2">
            Select every texture tag that applies.
          </div>
        </div>
      )
    case 'whatbeats':
      return (
        <div className="flex flex-col items-center gap-4 rounded-xl bg-panel/40 p-5">
          <div className="flex flex-col items-center gap-1">
            <span className="text-xs uppercase tracking-wide text-onfelt-3">Your hand</span>
            <div className="flex gap-2">
              {spot.hole.map((c) => (
                <Card key={c} card={c} size="md" />
              ))}
            </div>
          </div>
          <BoardRow cards={spot.board} />
          <div className="text-center text-sm text-onfelt-2">
            Which hand classes could an opponent hold that <strong>beat you</strong>?
          </div>
        </div>
      )
    case 'range':
      return (
        <div className="flex flex-col items-center gap-4 rounded-xl bg-panel/40 p-5">
          <div className="rounded-lg bg-panel/60 px-3 py-1.5 text-sm font-semibold text-onfelt-2">
            {spot.scenario.text}
          </div>
          <BoardRow cards={spot.flop} />
          <div className="text-center text-sm text-onfelt-2">
            Whose <Term id="range">range</Term> does this <Term id="flop">flop</Term> favor?
          </div>
        </div>
      )
    default:
      return null
  }
}

// ---------- per-drill answer input ----------

function renderInput(spot, { selected, toggle, submit }) {
  if (spot.type === 'range') {
    const OPTIONS = [
      { value: 'raiser', label: 'Raiser' },
      { value: 'neutral', label: 'Neutral' },
      { value: 'caller', label: 'Caller' },
    ]
    return (
      <div className="flex flex-wrap justify-center gap-3">
        {OPTIONS.map((o) => (
          <button
            key={o.value}
            onClick={() => submit(o.value)}
            className="rounded-xl bg-accent-hover px-6 py-3 text-lg font-bold text-onfelt shadow transition hover:bg-accent-bright"
          >
            {o.label}
          </button>
        ))}
      </div>
    )
  }

  // Multi-select drills: texture (tag chips) and whatbeats (hand-class chips).
  const options = spot.type === 'texture' ? TEXTURE_TAGS : HAND_CLASSES
  return (
    <div className="flex flex-col items-center gap-4">
      <div className="flex flex-wrap justify-center gap-2">
        {options.map((opt) => {
          const active = selected.includes(opt)
          return (
            <button
              key={opt}
              onClick={() => toggle(opt)}
              className={`pt-toggle ${
                active ? 'pt-toggle-on ring-2 ring-accent-bright' : 'pt-toggle-off'
              }`}
            >
              {opt}
            </button>
          )
        })}
      </div>
      <button
        onClick={() => submit(selected)}
        className="rounded-xl bg-accent-hover px-8 py-3 font-bold text-onfelt shadow hover:bg-accent-bright"
      >
        Submit{spot.type === 'whatbeats' && selected.length === 0 ? ' (nothing beats me)' : ''}
      </button>
      {spot.type === 'texture' && (
        <p className="text-xs text-onfelt-3">
          What do these mean? Tap:{' '}
          {TEXTURE_TAGS.map((tag, i) => (
            <span key={tag}>
              {i > 0 && ' · '}
              <Term id={tag}>{tag}</Term>
            </span>
          ))}
        </p>
      )}
    </div>
  )
}

function BoardRow({ cards }) {
  return (
    <div className="flex flex-col items-center gap-1">
      <span className="text-xs uppercase tracking-wide text-onfelt-3">
        <Term id="board">Board</Term>
      </span>
      <div className="flex gap-2">
        {cards.map((c) => (
          <Card key={c} card={c} size="md" />
        ))}
      </div>
    </div>
  )
}

// Shared page frame (matches the other trainers).
function Shell({ children }) {
  return <div className="pt-screen pt-screen-center">{children}</div>
}
