// Module 2 — Pot Odds & Equity Trainer (CLAUDE.md §4).
//
// Four selectable drills (Pot Odds, Outs, Rule of 2 & 4, Combined Verdict). Each
// spot is generated by ./drills.js, graded instantly, and wired into the shared
// store for progress + leak tracking. Layout mirrors the Range Trainer's
// setup → playing → summary flow.

import { useState } from 'react'
import Card from '../../components/Card.jsx'
import Term from '../../components/Term.jsx'
import { getProgress, recordAttempt, recordLeak, resetProgress, clearLeaks } from '../../store'
import {
  DRILL_TYPES,
  TYPE_LABEL,
  LEAK_PREFIX,
  LEAK_TAG,
  nextSpot,
  gradeSpot,
} from './drills.js'

const MODULE_ID = 'odds-trainer'
const SESSION_LENGTHS = [10, 25, 50, 100]

// Drill options for the setup screen. `null` = All (mixed) — the default.
const DRILL_OPTIONS = [
  { label: 'All (mixed)', value: null },
  ...DRILL_TYPES.map((t) => ({ label: TYPE_LABEL[t], value: t })),
]

const emptyStats = () => ({ answered: 0, correct: 0 })

export default function OddsTrainer() {
  const [phase, setPhase] = useState('setup') // 'setup' | 'playing' | 'summary'
  const [length, setLength] = useState(25)
  const [drill, setDrill] = useState(null) // null = All (mixed); else a DRILL_TYPES value
  const [spot, setSpot] = useState(null)
  const [generating, setGenerating] = useState(false)
  const [input, setInput] = useState('') // text field for numeric drills
  const [result, setResult] = useState(null) // { correct, correctText, explain }
  const [stats, setStats] = useState(emptyStats)
  const [sessionMisses, setSessionMisses] = useState({}) // drill type -> count
  const [lifetime, setLifetime] = useState(() => getProgress(MODULE_ID).accuracy)
  const [confirmingReset, setConfirmingReset] = useState(false)

  // Generating the combined-verdict spot runs Monte Carlo, so defer to a tick so
  // the "Dealing…" state can paint first. Uniform path for every drill type.
  const loadNext = () => {
    setGenerating(true)
    setInput('')
    setResult(null)
    setTimeout(() => {
      setSpot(nextSpot(drill))
      setGenerating(false)
    }, 0)
  }

  const start = (len) => {
    setLength(len)
    setStats(emptyStats())
    setSessionMisses({})
    setPhase('playing')
    loadNext()
  }

  const submit = (value) => {
    if (result || !spot) return // already graded, or nothing to grade
    const res = gradeSpot(spot, value)

    const progress = recordAttempt(MODULE_ID, { correct: res.correct })
    setLifetime(progress.accuracy)
    setStats((s) => ({ answered: s.answered + 1, correct: s.correct + (res.correct ? 1 : 0) }))

    if (!res.correct) {
      recordLeak(LEAK_TAG[spot.type], { type: spot.type, label: TYPE_LABEL[spot.type] })
      setSessionMisses((m) => ({ ...m, [spot.type]: (m[spot.type] ?? 0) + 1 }))
    }

    setResult(res)
  }

  const submitNumber = () => {
    if (input.trim() === '') return
    submit(Number(input))
  }

  const next = () => {
    if (stats.answered >= length) {
      setPhase('summary')
      return
    }
    loadNext()
  }

  // Clear only the odds-trainer's stored progress and its own leaks (tags with the
  // odds_ prefix); other modules' data is untouched.
  const confirmReset = () => {
    resetProgress(MODULE_ID)
    clearLeaks((leak) => leak.tag.startsWith(LEAK_PREFIX))
    setLifetime(getProgress(MODULE_ID).accuracy)
    setConfirmingReset(false)
  }

  const sessionAcc = stats.answered ? (100 * stats.correct) / stats.answered : 0
  const worstMisses = Object.entries(sessionMisses)
    .map(([type, count]) => ({ type, count }))
    .sort((a, b) => b.count - a.count)

  // ---------- setup ----------
  if (phase === 'setup') {
    return (
      <Shell>
        <h1 className="pt-title">Pot Odds &amp; Equity Trainer</h1>
        <p className="pt-subtitle">Table math — pot odds, outs, and the call/fold verdict</p>

        <p className="mt-6 text-sm text-onfelt-2">Choose a drill:</p>
        <div className="mt-2 flex flex-wrap justify-center gap-2">
          {DRILL_OPTIONS.map((opt) => {
            const active = drill === opt.value
            return (
              <button
                key={opt.label}
                onClick={() => setDrill(opt.value)}
                className={`pt-toggle ${active ? 'pt-toggle-on' : 'pt-toggle-off'}`}
              >
                {opt.label}
              </button>
            )
          })}
        </div>

        <p className="mt-6 text-sm text-onfelt-2">Choose a session length:</p>
        <div className="mt-2 flex flex-wrap justify-center gap-3">
          {SESSION_LENGTHS.map((len) => (
            <button
              key={len}
              onClick={() => start(len)}
              className="pt-btn pt-btn-light"
            >
              {len} spots
            </button>
          ))}
        </div>

        <div className="mt-6 flex flex-col items-center gap-1">
          <p className="text-xs text-onfelt-3">Lifetime accuracy: {lifetime.toFixed(1)}%</p>
          {!confirmingReset ? (
            <button
              onClick={() => setConfirmingReset(true)}
              className="text-xs text-onfelt-4 underline underline-offset-2 hover:text-onfelt-2"
            >
              Reset lifetime stats
            </button>
          ) : (
            <div className="mt-1 flex flex-col items-center gap-2 rounded-lg bg-panel/40 px-4 py-3">
              <p className="max-w-xs text-center text-xs text-onfelt-2">
                This clears all saved progress and leaks for the odds trainer — are you sure?
              </p>
              <div className="flex gap-2">
                <button
                  onClick={confirmReset}
                  className="rounded-lg bg-danger-solid px-3 py-1.5 text-xs font-semibold text-onfelt shadow hover:bg-danger-hover"
                >
                  Yes, reset
                </button>
                <button
                  onClick={() => setConfirmingReset(false)}
                  className="rounded-lg bg-surface px-3 py-1.5 text-xs font-semibold text-ink-heading shadow hover:bg-surface-inset"
                >
                  Cancel
                </button>
              </div>
            </div>
          )}
        </div>
      </Shell>
    )
  }

  // ---------- summary ----------
  if (phase === 'summary') {
    return (
      <Shell>
        <h1 className="pt-title">Session complete</h1>
        <div className="mt-4 pt-card p-5 text-center">
          <div className="text-4xl font-bold text-accent-text">{sessionAcc.toFixed(0)}%</div>
          <div className="text-sm text-ink-body">
            {stats.correct}/{stats.answered} correct · lifetime {lifetime.toFixed(1)}%
          </div>
        </div>

        <div className="mt-4 w-full max-w-sm pt-card p-4">
          <div className="text-sm font-semibold text-ink">Weakest drills this session</div>
          {worstMisses.length === 0 ? (
            <div className="mt-1 text-sm text-accent-text">No misses — clean session! 🎉</div>
          ) : (
            <ul className="mt-2 space-y-1 text-sm text-ink-body">
              {worstMisses.map((m) => (
                <li key={m.type} className="flex justify-between">
                  <span>{TYPE_LABEL[m.type]}</span>
                  <span className="tabular-nums text-danger">×{m.count}</span>
                </li>
              ))}
            </ul>
          )}
        </div>

        <button
          onClick={() => setPhase('setup')}
          className="mt-6 pt-btn pt-btn-light"
        >
          New session
        </button>
      </Shell>
    )
  }

  // ---------- playing ----------
  const spotNo = Math.min(stats.answered + (result ? 0 : 1), length)
  return (
    <Shell>
      <div className="flex w-full max-w-md items-center justify-between text-sm text-onfelt-2">
        <span>
          Spot {spotNo} / {length}
        </span>
        <span>
          Session {sessionAcc.toFixed(0)}% · Lifetime {lifetime.toFixed(0)}%
        </span>
      </div>

      {generating || !spot ? (
        <div className="mt-16 text-onfelt-2">Dealing…</div>
      ) : (
        <>
          <div className="mt-4 text-xs uppercase tracking-wide text-onfelt-3">
            {TYPE_LABEL[spot.type]}
          </div>

          <div className="mt-3 w-full max-w-md">{renderPrompt(spot)}</div>

          {!result ? (
            <div className="mt-6 w-full max-w-md">{renderInput(spot, { input, setInput, submitNumber, submit })}</div>
          ) : (
            <div className="mt-6 flex w-full max-w-md flex-col items-center gap-3">
              <div
                className={`w-full rounded-xl p-4 text-center shadow-lg ${
                  result.correct ? 'bg-surface-inset' : 'bg-danger-soft'
                }`}
              >
                <div
                  className={`text-lg font-bold ${
                    result.correct ? 'text-accent-text' : 'text-danger-text'
                  }`}
                >
                  {result.correct ? 'Correct' : 'Incorrect'} — {result.correctText}
                </div>
                <div className="mt-1 text-sm text-ink-body">{result.explain}</div>
              </div>
              <button
                onClick={next}
                className="rounded-xl bg-surface px-8 py-3 font-semibold text-ink-heading shadow hover:bg-surface-inset"
              >
                {stats.answered >= length ? 'See summary' : 'Next spot'}
              </button>
            </div>
          )}
        </>
      )}
    </Shell>
  )
}

// ---------- per-drill prompt rendering ----------

function renderPrompt(spot) {
  switch (spot.type) {
    case 'potodds':
      return (
        <div className="rounded-xl bg-panel/40 p-5 text-center text-onfelt">
          <div className="text-sm text-onfelt-2">
            <Term id="pot">Pot</Term>
          </div>
          <div className="text-3xl font-bold">${spot.pot}</div>
          <div className="mt-3 text-sm text-onfelt-2">Opponent bets</div>
          <div className="text-3xl font-bold">${spot.bet}</div>
          <div className="mt-4 text-sm text-onfelt-2">
            What <Term id="equity">equity</Term> % do you need to call?
          </div>
        </div>
      )
    case 'outs':
      return (
        <div className="flex flex-col items-center gap-4 rounded-xl bg-panel/40 p-5">
          <BoardAndHand hole={spot.hole} board={spot.board} />
          <div className="text-center text-sm text-onfelt-2">
            How many <Term id="outs">outs</Term> does your <Term id="draw">draw</Term> have?
          </div>
        </div>
      )
    case 'ruleof24':
      return (
        <div className="rounded-xl bg-panel/40 p-5 text-center text-onfelt">
          <div className="text-3xl font-bold">{spot.outs} outs</div>
          <div className="mt-2 text-onfelt-2">
            {spot.cardsToCome === 2 ? 'Two cards to come (flop → river)' : 'One card to come (turn → river)'}
          </div>
          <div className="mt-4 text-sm text-onfelt-2">
            Estimate your <Term id="equity">equity</Term> % with the Rule of 2 &amp; 4.
          </div>
        </div>
      )
    case 'combined':
      return (
        <div className="flex flex-col items-center gap-4 rounded-xl bg-panel/40 p-5">
          <BoardAndHand hole={spot.hole} board={spot.board} />
          <div className="text-center text-onfelt">
            <span className="text-sm text-onfelt-2"><Term id="pot">Pot</Term> </span>
            <span className="font-bold">${spot.pot}</span>
            <span className="mx-2 text-onfelt-4">·</span>
            <span className="text-sm text-onfelt-2">Opponent bets </span>
            <span className="font-bold">${spot.bet}</span>
          </div>
          <div className="text-center text-sm text-onfelt-2">Call or fold?</div>
        </div>
      )
    default:
      return null
  }
}

// ---------- per-drill answer input ----------

function renderInput(spot, { input, setInput, submitNumber, submit }) {
  if (spot.type === 'combined') {
    return (
      <div className="flex flex-wrap justify-center gap-3">
        <button
          onClick={() => submit('call')}
          className="rounded-xl bg-accent-hover px-7 py-3 text-lg font-bold text-onfelt shadow transition hover:bg-accent-bright"
        >
          Call
        </button>
        <button
          onClick={() => submit('fold')}
          className="rounded-xl bg-danger-solid px-7 py-3 text-lg font-bold text-onfelt shadow transition hover:bg-danger-hover"
        >
          Fold
        </button>
      </div>
    )
  }

  // Numeric drills: potodds, outs, ruleof24.
  const suffix = spot.type === 'outs' ? 'outs' : '%'
  return (
    <div className="flex justify-center gap-2">
      <div className="flex items-center rounded-xl bg-surface px-3 shadow">
        <input
          type="number"
          autoFocus
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && submitNumber()}
          className="w-24 bg-transparent py-3 text-lg font-semibold text-ink-heading outline-none"
          placeholder="?"
        />
        <span className="pl-1 text-sm text-ink-muted">{suffix}</span>
      </div>
      <button
        onClick={submitNumber}
        className="rounded-xl bg-accent-hover px-6 py-3 font-bold text-onfelt shadow hover:bg-accent-bright"
      >
        Submit
      </button>
    </div>
  )
}

function BoardAndHand({ hole, board }) {
  return (
    <div className="flex flex-col items-center gap-3">
      <div className="flex flex-col items-center gap-1">
        <span className="text-xs uppercase tracking-wide text-onfelt-3">Your hand</span>
        <div className="flex gap-2">
          {hole.map((c) => (
            <Card key={c} card={c} size="md" />
          ))}
        </div>
      </div>
      <div className="flex flex-col items-center gap-1">
        <span className="text-xs uppercase tracking-wide text-onfelt-3">Board</span>
        <div className="flex gap-2">
          {board.map((c) => (
            <Card key={c} card={c} size="sm" />
          ))}
        </div>
      </div>
    </div>
  )
}

// Shared page frame (matches the Range Trainer).
function Shell({ children }) {
  return <div className="pt-screen pt-screen-center">{children}</div>
}
