// Module 2 — Pot Odds & Equity Trainer (CLAUDE.md §4).
//
// Four selectable drills (Pot Odds, Outs, Rule of 2 & 4, Combined Verdict). Each
// spot is generated by ./drills.js, graded instantly, and wired into the shared
// store for progress + leak tracking. Layout mirrors the Range Trainer's
// setup → playing → summary flow.

import { useState } from 'react'
import Card from '../../components/Card.jsx'
import { getProgress, recordAttempt, recordLeak, resetProgress, clearLeaks } from '../../store'
import {
  DRILL_TYPES,
  TYPE_LABEL,
  LEAK_PREFIX,
  LEAK_TAG,
  nextSpot,
  gradeSpot,
} from './drills.js'

const MODULE_ID = 'odds-trainer'
const SESSION_LENGTHS = [10, 25, 50, 100]

// Drill options for the setup screen. `null` = All (mixed) — the default.
const DRILL_OPTIONS = [
  { label: 'All (mixed)', value: null },
  ...DRILL_TYPES.map((t) => ({ label: TYPE_LABEL[t], value: t })),
]

const emptyStats = () => ({ answered: 0, correct: 0 })

export default function OddsTrainer() {
  const [phase, setPhase] = useState('setup') // 'setup' | 'playing' | 'summary'
  const [length, setLength] = useState(25)
  const [drill, setDrill] = useState(null) // null = All (mixed); else a DRILL_TYPES value
  const [spot, setSpot] = useState(null)
  const [generating, setGenerating] = useState(false)
  const [input, setInput] = useState('') // text field for numeric drills
  const [result, setResult] = useState(null) // { correct, correctText, explain }
  const [stats, setStats] = useState(emptyStats)
  const [sessionMisses, setSessionMisses] = useState({}) // drill type -> count
  const [lifetime, setLifetime] = useState(() => getProgress(MODULE_ID).accuracy)
  const [confirmingReset, setConfirmingReset] = useState(false)

  // Generating the combined-verdict spot runs Monte Carlo, so defer to a tick so
  // the "Dealing…" state can paint first. Uniform path for every drill type.
  const loadNext = () => {
    setGenerating(true)
    setInput('')
    setResult(null)
    setTimeout(() => {
      setSpot(nextSpot(drill))
      setGenerating(false)
    }, 0)
  }

  const start = (len) => {
    setLength(len)
    setStats(emptyStats())
    setSessionMisses({})
    setPhase('playing')
    loadNext()
  }

  const submit = (value) => {
    if (result || !spot) return // already graded, or nothing to grade
    const res = gradeSpot(spot, value)

    const progress = recordAttempt(MODULE_ID, { correct: res.correct })
    setLifetime(progress.accuracy)
    setStats((s) => ({ answered: s.answered + 1, correct: s.correct + (res.correct ? 1 : 0) }))

    if (!res.correct) {
      recordLeak(LEAK_TAG[spot.type], { type: spot.type, label: TYPE_LABEL[spot.type] })
      setSessionMisses((m) => ({ ...m, [spot.type]: (m[spot.type] ?? 0) + 1 }))
    }

    setResult(res)
  }

  const submitNumber = () => {
    if (input.trim() === '') return
    submit(Number(input))
  }

  const next = () => {
    if (stats.answered >= length) {
      setPhase('summary')
      return
    }
    loadNext()
  }

  // Clear only the odds-trainer's stored progress and its own leaks (tags with the
  // odds_ prefix); other modules' data is untouched.
  const confirmReset = () => {
    resetProgress(MODULE_ID)
    clearLeaks((leak) => leak.tag.startsWith(LEAK_PREFIX))
    setLifetime(getProgress(MODULE_ID).accuracy)
    setConfirmingReset(false)
  }

  const sessionAcc = stats.answered ? (100 * stats.correct) / stats.answered : 0
  const worstMisses = Object.entries(sessionMisses)
    .map(([type, count]) => ({ type, count }))
    .sort((a, b) => b.count - a.count)

  // ---------- setup ----------
  if (phase === 'setup') {
    return (
      <Shell>
        <h1 className="text-2xl font-bold text-white">Pot Odds &amp; Equity Trainer</h1>
        <p className="text-emerald-100">Table math — pot odds, outs, and the call/fold verdict</p>

        <p className="mt-6 text-sm text-emerald-200">Choose a drill:</p>
        <div className="mt-2 flex flex-wrap justify-center gap-2">
          {DRILL_OPTIONS.map((opt) => {
            const active = drill === opt.value
            return (
              <button
                key={opt.label}
                onClick={() => setDrill(opt.value)}
                className={`rounded-lg px-4 py-2 text-sm font-semibold shadow transition ${
                  active
                    ? 'bg-white text-emerald-900'
                    : 'bg-emerald-700 text-emerald-50 hover:bg-emerald-600'
                }`}
              >
                {opt.label}
              </button>
            )
          })}
        </div>

        <p className="mt-6 text-sm text-emerald-200">Choose a session length:</p>
        <div className="mt-2 flex flex-wrap justify-center gap-3">
          {SESSION_LENGTHS.map((len) => (
            <button
              key={len}
              onClick={() => start(len)}
              className="rounded-xl bg-white px-6 py-3 font-semibold text-emerald-900 shadow hover:bg-emerald-50"
            >
              {len} spots
            </button>
          ))}
        </div>

        <div className="mt-6 flex flex-col items-center gap-1">
          <p className="text-xs text-emerald-300">Lifetime accuracy: {lifetime.toFixed(1)}%</p>
          {!confirmingReset ? (
            <button
              onClick={() => setConfirmingReset(true)}
              className="text-xs text-emerald-400 underline underline-offset-2 hover:text-emerald-200"
            >
              Reset lifetime stats
            </button>
          ) : (
            <div className="mt-1 flex flex-col items-center gap-2 rounded-lg bg-emerald-950/40 px-4 py-3">
              <p className="max-w-xs text-center text-xs text-emerald-100">
                This clears all saved progress and leaks for the odds trainer — are you sure?
              </p>
              <div className="flex gap-2">
                <button
                  onClick={confirmReset}
                  className="rounded-lg bg-rose-500 px-3 py-1.5 text-xs font-semibold text-white shadow hover:bg-rose-400"
                >
                  Yes, reset
                </button>
                <button
                  onClick={() => setConfirmingReset(false)}
                  className="rounded-lg bg-white px-3 py-1.5 text-xs font-semibold text-emerald-900 shadow hover:bg-emerald-50"
                >
                  Cancel
                </button>
              </div>
            </div>
          )}
        </div>
      </Shell>
    )
  }

  // ---------- summary ----------
  if (phase === 'summary') {
    return (
      <Shell>
        <h1 className="text-2xl font-bold text-white">Session complete</h1>
        <div className="mt-4 rounded-xl bg-white/95 p-5 text-center shadow-lg">
          <div className="text-4xl font-bold text-emerald-700">{sessionAcc.toFixed(0)}%</div>
          <div className="text-sm text-gray-600">
            {stats.correct}/{stats.answered} correct · lifetime {lifetime.toFixed(1)}%
          </div>
        </div>

        <div className="mt-4 w-full max-w-sm rounded-xl bg-white/95 p-4 shadow-lg">
          <div className="text-sm font-semibold text-gray-800">Weakest drills this session</div>
          {worstMisses.length === 0 ? (
            <div className="mt-1 text-sm text-emerald-700">No misses — clean session! 🎉</div>
          ) : (
            <ul className="mt-2 space-y-1 text-sm text-gray-700">
              {worstMisses.map((m) => (
                <li key={m.type} className="flex justify-between">
                  <span>{TYPE_LABEL[m.type]}</span>
                  <span className="tabular-nums text-red-600">×{m.count}</span>
                </li>
              ))}
            </ul>
          )}
        </div>

        <button
          onClick={() => setPhase('setup')}
          className="mt-6 rounded-xl bg-white px-6 py-3 font-semibold text-emerald-900 shadow hover:bg-emerald-50"
        >
          New session
        </button>
      </Shell>
    )
  }

  // ---------- playing ----------
  const spotNo = Math.min(stats.answered + (result ? 0 : 1), length)
  return (
    <Shell>
      <div className="flex w-full max-w-md items-center justify-between text-sm text-emerald-100">
        <span>
          Spot {spotNo} / {length}
        </span>
        <span>
          Session {sessionAcc.toFixed(0)}% · Lifetime {lifetime.toFixed(0)}%
        </span>
      </div>

      {generating || !spot ? (
        <div className="mt-16 text-emerald-100">Dealing…</div>
      ) : (
        <>
          <div className="mt-4 text-xs uppercase tracking-wide text-emerald-300">
            {TYPE_LABEL[spot.type]}
          </div>

          <div className="mt-3 w-full max-w-md">{renderPrompt(spot)}</div>

          {!result ? (
            <div className="mt-6 w-full max-w-md">{renderInput(spot, { input, setInput, submitNumber, submit })}</div>
          ) : (
            <div className="mt-6 flex w-full max-w-md flex-col items-center gap-3">
              <div
                className={`w-full rounded-xl p-4 text-center shadow-lg ${
                  result.correct ? 'bg-emerald-50' : 'bg-rose-50'
                }`}
              >
                <div
                  className={`text-lg font-bold ${
                    result.correct ? 'text-emerald-700' : 'text-rose-700'
                  }`}
                >
                  {result.correct ? 'Correct' : 'Incorrect'} — {result.correctText}
                </div>
                <div className="mt-1 text-sm text-gray-700">{result.explain}</div>
              </div>
              <button
                onClick={next}
                className="rounded-xl bg-white px-8 py-3 font-semibold text-emerald-900 shadow hover:bg-emerald-50"
              >
                {stats.answered >= length ? 'See summary' : 'Next spot'}
              </button>
            </div>
          )}
        </>
      )}
    </Shell>
  )
}

// ---------- per-drill prompt rendering ----------

function renderPrompt(spot) {
  switch (spot.type) {
    case 'potodds':
      return (
        <div className="rounded-xl bg-emerald-950/40 p-5 text-center text-white">
          <div className="text-sm text-emerald-200">Pot</div>
          <div className="text-3xl font-bold">${spot.pot}</div>
          <div className="mt-3 text-sm text-emerald-200">Opponent bets</div>
          <div className="text-3xl font-bold">${spot.bet}</div>
          <div className="mt-4 text-sm text-emerald-100">
            What equity % do you need to call?
          </div>
        </div>
      )
    case 'outs':
      return (
        <div className="flex flex-col items-center gap-4 rounded-xl bg-emerald-950/40 p-5">
          <BoardAndHand hole={spot.hole} board={spot.board} />
          <div className="text-center text-sm text-emerald-100">
            How many outs does your draw have?
          </div>
        </div>
      )
    case 'ruleof24':
      return (
        <div className="rounded-xl bg-emerald-950/40 p-5 text-center text-white">
          <div className="text-3xl font-bold">{spot.outs} outs</div>
          <div className="mt-2 text-emerald-100">
            {spot.cardsToCome === 2 ? 'Two cards to come (flop → river)' : 'One card to come (turn → river)'}
          </div>
          <div className="mt-4 text-sm text-emerald-100">
            Estimate your equity % with the Rule of 2 &amp; 4.
          </div>
        </div>
      )
    case 'combined':
      return (
        <div className="flex flex-col items-center gap-4 rounded-xl bg-emerald-950/40 p-5">
          <BoardAndHand hole={spot.hole} board={spot.board} />
          <div className="text-center text-white">
            <span className="text-sm text-emerald-200">Pot </span>
            <span className="font-bold">${spot.pot}</span>
            <span className="mx-2 text-emerald-400">·</span>
            <span className="text-sm text-emerald-200">Opponent bets </span>
            <span className="font-bold">${spot.bet}</span>
          </div>
          <div className="text-center text-sm text-emerald-100">Call or fold?</div>
        </div>
      )
    default:
      return null
  }
}

// ---------- per-drill answer input ----------

function renderInput(spot, { input, setInput, submitNumber, submit }) {
  if (spot.type === 'combined') {
    return (
      <div className="flex justify-center gap-4">
        <button
          onClick={() => submit('call')}
          className="rounded-xl bg-emerald-500 px-8 py-3 text-lg font-bold text-white shadow hover:bg-emerald-400"
        >
          Call
        </button>
        <button
          onClick={() => submit('fold')}
          className="rounded-xl bg-rose-500 px-8 py-3 text-lg font-bold text-white shadow hover:bg-rose-400"
        >
          Fold
        </button>
      </div>
    )
  }

  // Numeric drills: potodds, outs, ruleof24.
  const suffix = spot.type === 'outs' ? 'outs' : '%'
  return (
    <div className="flex justify-center gap-2">
      <div className="flex items-center rounded-xl bg-white px-3 shadow">
        <input
          type="number"
          autoFocus
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && submitNumber()}
          className="w-24 bg-transparent py-3 text-lg font-semibold text-emerald-900 outline-none"
          placeholder="?"
        />
        <span className="pl-1 text-sm text-gray-500">{suffix}</span>
      </div>
      <button
        onClick={submitNumber}
        className="rounded-xl bg-emerald-500 px-6 py-3 font-bold text-white shadow hover:bg-emerald-400"
      >
        Submit
      </button>
    </div>
  )
}

function BoardAndHand({ hole, board }) {
  return (
    <div className="flex flex-col items-center gap-3">
      <div className="flex flex-col items-center gap-1">
        <span className="text-xs uppercase tracking-wide text-emerald-300">Your hand</span>
        <div className="flex gap-2">
          {hole.map((c) => (
            <Card key={c} card={c} size="md" />
          ))}
        </div>
      </div>
      <div className="flex flex-col items-center gap-1">
        <span className="text-xs uppercase tracking-wide text-emerald-300">Board</span>
        <div className="flex gap-2">
          {board.map((c) => (
            <Card key={c} card={c} size="sm" />
          ))}
        </div>
      </div>
    </div>
  )
}

// Shared page frame (matches the Range Trainer).
function Shell({ children }) {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-emerald-800 p-6">
      {children}
    </div>
  )
}
